
select * from tb_Museu;
drop table tb_Museu;
drop table tb_obra;
insert into tb_Museu (nome, endereco, email, numero, descri, img,historia)
values
("Museu de Arte de São Paulo (MASP)", "Cidade de São Paulo - Bela Vista", "XXX", "11931495959", "Arte ocidental nacional e estrangeira", "https://www.melhoresdestinos.com.br/wp-content/uploads/2019/02/passagens-aereas-sao-paulo-capa2019-02-820x430.jpg", "Museu de Arte de São Paulo Assis Chateaubriand (mais conhecido pelo acrônimo MASP) é um centro cultural e museu de arte brasileiro concebido em 1947 idealizado pelo jornalista paraibano Assis Cha	teaubriand. Entre os anos de 1947 e 1990, o crítico e marchand italiano Pietro Bardi assumiu a direção do MASP a convite de Chateaubriand.[1] Situado desde 7 de novembro de 1968, na Avenida Paulista, cidade de São Paulo (estado homônimo), em um edifício projetado pela arquiteta ítalo-brasileira Lina Bo Bardi para ser sua sede, é considerado uma das mais importantes instituições culturais brasileiras."),
 
("Museu Paulista da Universidade de São Paulo", "Cidade de São Paulo - Ipiranga", "XXX", "1120658000", "Museu sobre a independência brasileira e o período histórico correspondente","https://sites.usp.br/ciclocuratorial/wp-content/uploads/sites/557/2020/01/menor_1280px-Webysther_20190304150324_-_Parque_da_Independ%C3%AAncia.jpg", "Museu Paulista da Universidade de São Paulo, também conhecido como Museu do Ipiranga ou Museu Paulista, é o museu público mais antigo da cidade de São Paulo, cuja sede é um monumento-edifício que faz parte do conjunto arquitetônico do Parque da Independência. É o mais importante museu da Universidade de São Paulo e um dos mais visitados da capital paulista. O museu foi inaugurado oficialmente em 7 de setembro de 1895 com o nome Museu de História Natural. Este importante símbolo da Independência do Brasil está vinculado à Universidade de São Paulo desde 1963, como uma instituição científica, cultural e educacional que exerce pesquisa, ensino e extensão com atuação no campo da História. É responsável por um grande acervo de objetos, mobiliário e obras de arte com relevância histórica, especialmente aquelas que possuem alguma relação com a independência do Brasil e o período histórico correspondente."),

("Museu do Futebol","Cidade de São Paulo - Pacaembu","contato@museudofutebol.org.br","113664-3848","Museu sobre o futebol nacional","https://museudofutebol.org.br/wp-content/uploads/2020/09/MF_0168-Marcos-LopesRED-1024x682.png","O museu conta a história do futebol desde seu início no Brasil até os dias atuais. Durante o passeio, aspectos como a relação do esporte com a arte, a história das Copas do Mundo, o impacto do futebol na vida das pessoas em geral são explicados. Os visitantes têm acesso, a partir de experiências sonoras e visuais, a uma sequência de informações didáticas e ilustrativas que relacionam o esporte à vida dos brasileiros no século XX."),

("Museu da Língua Portuguesa", "Cidade de São Paulo - Luz", "museu@museulp.org.br", "114470-1515", "Museu sobre a língua materna do Brasil","https://www.museudalinguaportuguesa.org.br/wp-content/uploads/2021/07/01-1.jpg","Museu da Língua Portuguesa ou Estação Luz da Nossa Língua MHCa é um museu interativo sobre a língua portuguesa localizado na cidade de São Paulo, Brasil, no histórico edifício Estação da Luz, no Bairro da Luz, região central da cidade. Foi concebido pela Secretaria da Cultura do Estado de São Paulo em conjunto com a Fundação Roberto Marinho, tendo um investimento de cerca de 37 milhões de reais. O objetivo da instituição é criar um espaço vivo sobre a língua portuguesa, considerada como base da cultura do Brasil, onde seja possível causar surpresa nos visitantes com os aspectos inusitados e, muitas vezes, desconhecidos de sua língua materna. Segundo os organizadores do museu, deseja-se que, no museu, esse público tenha acesso a novos conhecimentos e reflexões, de maneira intensa e prazerosa"),

(" Museu da Polícia Civil do Estado de São Paulo"," Cidade de São Paulo - Butantã","museu.acadepol@policiacivil.sp.gov.br","113468-3360",
"Seu objetivo é preservar um acervo constituído por documentos de inquéritos policiais, tais como as diferentes armas utilizadas pelos civis, tatuagens típicas das cadeias, tragédias no trânsito, objetos usados em delitos e todas as outras situações que envolvem a criminalidade paulista a partir do século XX.", "https://static.tvgazeta.com.br/uploads/2021/11/museu-policia-civil2.png","Fundado em 1927, foi nomeado inicialmente como Museu de Técnica Policial e de História do Crime. O museu foi legalmente instituído pelo Decreto Nº 4.715 em 23 de abril de 1930. Inicialmente, a instituição não era aberta ao público, sendo apenas objeto de estudos para os alunos da Acadepol. O espaço se tornou acessível à toda população, com entrada gratuita, no ano de 1952."),

("Museu do Amanhã","Cidade do Rio de Janeiro - RJ","contato@museudoamanha.org.br","213812-1812","Tudo sobre a identidade cultural e internacional da cidade do Rio de Janeiro", "https://museudoamanha.org.br/sites/default/files/Visite_1280x800_MdA-BernardLessa__1456509569_189.60.197.72.jpg","O Museu do Amanhã é um museu construído no município do Rio de Janeiro, no Brasil. O prédio, projeto do arquiteto espanhol Santiago Calatrava, foi erguido ao lado da Praça Mauá, na zona portuária (mais precisamente no Píer Mauá). Sua construção teve o apoio da Fundação Roberto Marinho e teve o custo total de cerca de 230 milhões de reais. O edifício foi inaugurado em 17 de dezembro de 2015 com a presença da então presidente do Brasil Dilma Rousseff e recebeu cerca de 25 mil visitantes em seu primeiro fim de semana de funcionamento."),

("Museu da Imigração do Estado de São Paulo","Cidade de São Paulo - Mooca","XXX","112692-1866","Museu sobre a imigração no Brasil", "https://www.saopaulo.sp.gov.br/wp-content/uploads/2016/12/Fachada-Vanessa-Canoso.jpg","A Hospedaria dos Imigrantes foi fundada no ano de 1887, ao longo da antiga linha ferroviária São Paulo Railway.[12] A construção do edifício, segundo a Sociedade Promotora da Imigração - formada por cafeicultores da época - tinha como principal objetivo promover a inserção dos imigrantes na província de São Paulo, e encaminha-los para trabalhos na agricultura, uma vez que o afluxo de pessoas de diferentes nacionalidades direcionadas às lavouras de café só aumentava. Era a partir do Porto de Santos que os imigrantes adentravam no Brasil com o objetivo de refazer suas vidas e, logo em seguida, eram levados até a Hospedaria, onde ficariam alojados durante um período variável de cinco a oito dias até serem enviados para iniciar o trabalho nas fazendas. Durante um período de noventa e um anos (1887-1978), a Hospedaria dos Imigrantes recebeu mais de 2,5 milhões de pessoas, de mais de 70 nacionalidades.");




insert into tb_obra (nome_obra, descri_obra, imagem, data_obra,idMuseu)
values 
("Princesa Marie Adélaïde da França - O ar", "Óleo sobre tela, 106 x 138 cm", "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Jean_marc_nattier_-_madame_marie-ad%C3%A9laide_de_France.jpg/1200px-Jean_marc_nattier_-_madame_marie-ad%C3%A9laide_de_France.jpg","31/05/2014",1),
("Trattato della Pittura","Obra por Leonardo da Vinci","https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Tratado_de_pintura_-_leonardo.jpg/800px-Tratado_de_pintura_-_leonardo.jpg","01/04/1792",1),
("Virgem com o Menino e São João Batista criança","Têmpera sobre madeira, 74 × 74 cm", "https://lh3.googleusercontent.com/ci/ALr3YSFJr1V7L8nJZrPTVirfd9YamZ73OI3ttcckDK4EL0scOd7nL7vOzenxiPiHiCHdePzY1p3-Ag=s1200", "07/09/1500",1),

("BRASÃO DE SÃO PAULO","SEGUNDO O LIVRO DO TOMBO: BRASÃO DE SÃO PAULO (ATÉ SUA MORTE ESTEVE PREGADO NA PORTA DE SEU QUARTO COMO HOMENAGEM DE SUA NETA REGINA E, DEPOIS DESTA GUARDADO PELA MESMA ENTRE SEUS PERTENCES DURANTE A REVOLUÇÃO DE 1932, A ASSOCIAÇÃO COMMERCIAL DE SÃO PAULO NOMEOU UMA COMISSÃO PARA DIRIGIR A CAMPANHA DO OURO, QUE ADOTOU O LEMA PRO SÃO PAULO FIANT EXIMIA - POR SÃO PAULO FAÇAM-SE GRANDES COUSAS. ESSA COMISSÃO, TAMBÉM ADOTOU COMO EMBLEMA, A ESPADA ROMANA USADA PELO APÓSTOLO SÃO PAULO, POSTA EM PALA COM A PONTA AO ALTO E O PUNHO SOBRE O CRUZAMENTO DE DOIS RAMOS, UM DE LOURO E OUTRO DE CARVALHO (O BRAZÃO DE ARMAS DO ESTADO DE SÃO PAULO 1932), SENDO UMA SUGESTÃO DO PINTOR JOSÉ WASTH RODRIGUES. O LEMA, ASSIM COMO O EMBLEMA, FORAM REPRODUZIDOS EM MEDALHAS, DIPLOMAS, ANÉIS E DISTINTIVOS DA CAMPANHA DO OURO","https://d1o6h00a1h5k7q.cloudfront.net/imagens/img_m/16385/7652571.jpg",  "22/08/1932",2),
("EXPLOSIVOS","USADA NA REVOLUÇÃO DE 32 PELO EXÉRCITO CONSTITUCIONALISTA. DURANTE A REVOLUÇÃO DE 1932, HOUVE UMA GRANDE PRODUÇÃO DE MUNIÇÕES E EXPLOSIVOS. AS GRANDES INDÚSTRIAS DO ESTADO DE SÃO PAULO FORAM ADAPTADAS PARA A PRODUÇÃO DE MATERIAL BÉLICO, COMO NADIR FIGUEIREDO, INDÚSTRIAS MATARAZZO, OFICINAS DAS COMPANHIAS FERROVIÁRIAS MOGIANA, PAULISTA E SOROCABANA DE ESTRADA DE FERRO, ENTRE OUTRAS.","https://media.istockphoto.com/id/1096095528/pt/foto/mortar-cannon-gun-isolated-white-background-mortar-from-the-second-world-war.jpg?s=170667a&w=0&k=20&c=Bmaz983ZT4j89Fv3LG4Pv_0ZrCuUyfbCgwfYUrJ3eIQ=","15/07/1932",2),
("MOEDA DA BAHIA","CRIADA PROVISORIAMENTE POR LEI DE 8.3.1694, A CASA DA MOEDA DA BAHIA INICIOU SUA ATIVIDADE SOMENTE NO ANO SEGUINTE, SOB A SUPERINTENDÊNCIA DE JOÃO DA ROCHA PITTA, SENDO ESTABELECIDOS OS ORDENADOS DOS EMPREGADOS EM 4.1.1695. (PROBER, 1947:21) - AVALIADA EM US$ 40,00 (QUARENTA DÓLARES) EM 10/06/1987, POR DIRCE T.SANTOS","https://1.bp.blogspot.com/-BifvcKeToIY/U3nbtySlPdI/AAAAAAAACwA/YsvUFBZRfxQ/s1600/anverso+1816+B.jpg","18/06/1695",2),

("Leila Silveira entrevista Pelé no gramado","Acervo Museu do Futebol | Coleção Leila Silveira | Direitos Reservados","https://museudofutebol.org.br/wp-content/uploads/2022/12/Design-sem-nome-1.jpg","18/05/1695",3),
("Mário de Andrade em sua casa na Barra Funda","Acervo IEB-USP | Foto: Victor Knoll.","https://museudofutebol.org.br/wp-content/uploads/2022/08/mario_de_andrade_VictorKnoll.webp","23/03/1935",3),
("Moacyr Barbosa e Clotilde Melônio.","Acervo Museu do Futebol | Coleção Moacyr Barbosa | Foto: Direitos Reservados","https://museudofutebol.org.br/wp-content/uploads/2022/04/Moacyr_Barbosa.jpg","19/07/1695",3),

(" Língua dos imigrantes","2º Pavimento - Viagens da Língua - Exposições","https://www.museudalinguaportuguesa.org.br/wp-content/uploads/2023/07/2222-223x300.jpg","04/06/2021",4),
("Saguão principal","2º Pavimento - Viagens da Língua - Exposições","https://www.cnnbrasil.com.br/viagemegastronomia/wp-content/uploads/sites/5/2022/01/museu-da-lingua-portuguesa.jpg","20/10/2021",4),
("Acesso da esquerda","Descrição: 2º Pavimento - Viagens da Língua - Exposições","https://istoe.com.br/wp-content/uploads/2021/02/museu-da-lingua-portuguesa.jpg",  "11/02/2021",4),

("Tatuagens encontradas no meio prisional","Foto - 2º Pavilhão","https://www.saopaulo.sp.gov.br/wp-content/uploads/2019/03/47444068241_ee91ed6af3_k-1024x683.jpg","13/06/2019",5),
("Luvas para perícia criminal","Depósito","https://www.policiacivil.sp.gov.br/portal/ShowProperty?nodeId=/dipolContent/UCM_033434//idcPrimaryFile&", "22/03/2021",5),
("Digitais e biometria","Quadro 1703","https://www.policiacivil.sp.gov.br/portal/ShowProperty?nodeId=/dipolContent/UCM_033441//idcPrimaryFile&", "24/04/2022",5),

("Exposição principal - Terra"," Visitantes acompanhando a seção Terra da exposição principal do Museu do Amanhã","https://conexaoplaneta.com.br/wp-content/uploads/2015/12/museu-do-amanha-terra.jpg","07/04/2017",6),
("Exposição principal - Antropoceno","Visitantes no centro dos painéis da seção Antropoceno da exposição principal do Museu do Amanhã","https://museudoamanha.org.br/sites/default/files/Antropoceno_1280x800_CidadeOlimpica1.jpg","09/08/2016",6),
("Oca Pavilhão Nós","Visitantes no centro da oca no pavilhão Nós. No meio da imagem, pode-se localizar a churinga de madeira.","https://infograficos.estadao.com.br/cidades/museu-do-amanha/img/extras/museu-nos.jpg","01/03/2015",6),

("Bilhetes de viagem","O Acervo Digital do Museu da Imigração reúne diferentes categorias de documentos que contribuem para o entendimento dos deslocamentos humanos do fim do século 19 ao início do século 20. Entre os arquivos, os bilhetes de viagem, importantes para o embarque, a travessia transatlântica e os trâmites necessários no local de destino, guardam informações interessantes e possibilitam descobertas sobre a experiência dos migrantes.","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvg_fryGEQz81N3HHSVqbhl1iiR59D1OCDXA&usqp=CAU","10/07/1800",7),
("Brasileiros na hospedaria","De acordo com os registros da Hospedaria de Imigrantes do Brás, a maior parte das pessoas abrigadas no edifício nasceu no Brasil! Assim sendo, do final do século XIX até o encerramento das atividades (na década de 1970), a instituição recebeu brasileiros em diversas condições: alunos, desalojados, desamparados, enfermos, migrantes, presos políticos, professores e mais.De acordo com os registros da Hospedaria de Imigrantes do Brás, a maior parte das pessoas abrigadas no edifício nasceu no Brasil! Assim sendo, do final do século XIX até o encerramento das atividades (na década de 1970), a instituição recebeu brasileiros em diversas condições: alunos, desalojados, desamparados, enfermos, migrantes, presos políticos, professores e mais.","https://museudaimigracao.org.br/uploads/blog/materias/chamada-12-08-2020-15-24.png", "14/09/1970",7),
("Brasileiros na hospedaria2","“Migrações à Mesa” foi uma exposição montada no Museu da Imigração em 2016. Com o intuito de discutir as relações entre alimentação e migração, foi realizada uma ação participativa pelas redes sociais para que migrantes e seus descendentes compartilhassem conosco seus cadernos de receita, objetos de cozinha e lembranças. Por meio da história de dez famílias, compreendemos a potência dos sabores na condução por memórias e afetos e no encurtamento de distâncias. Esta nova montagem conta exclusivamente com utensílios e entrevistas do acervo do Museu da Imigração, mas toda a abordagem é devida à generosidade dessas famílias, a quem agradecemos e dedicamos este projeto.","https://museudaimigracao.org.br/uploads/portal/eventos/exposicoes/untitled-design-2020-05-30t193015092-30-05-2020-22-37.png","25/10/2016",7);